/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform that provides scalable browser sessions and worker pool management.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  SessionMetrics
} from '.././model';

import { customInstance } from '.././mutator';




/**
 * Create performance metrics for a session (CPU, memory, network usage)
 * @summary Create session metrics
 */
export const postApiV1SessionsIdMetrics = (
    id: string,
    sessionMetrics: SessionMetrics,
 signal?: AbortSignal
) => {
      
      
      return customInstance<SessionMetrics>(
      {url: `/api/v1/sessions/${id}/metrics`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sessionMetrics, signal
    },
      );
    }
  


export const getPostApiV1SessionsIdMetricsMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SessionsIdMetrics>>, TError,{id: string;data: SessionMetrics}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postApiV1SessionsIdMetrics>>, TError,{id: string;data: SessionMetrics}, TContext> => {

const mutationKey = ['postApiV1SessionsIdMetrics'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV1SessionsIdMetrics>>, {id: string;data: SessionMetrics}> = (props) => {
          const {id,data} = props ?? {};

          return  postApiV1SessionsIdMetrics(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV1SessionsIdMetricsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV1SessionsIdMetrics>>>
    export type PostApiV1SessionsIdMetricsMutationBody = SessionMetrics
    export type PostApiV1SessionsIdMetricsMutationError = ErrorResponse

    /**
 * @summary Create session metrics
 */
export const usePostApiV1SessionsIdMetrics = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV1SessionsIdMetrics>>, TError,{id: string;data: SessionMetrics}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV1SessionsIdMetrics>>,
        TError,
        {id: string;data: SessionMetrics},
        TContext
      > => {

      const mutationOptions = getPostApiV1SessionsIdMetricsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    