/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

export interface AsynqWorkerInfo {
  /** Time the worker needs to finish processing the task by. */
  deadline?: string;
  /** Queue from which the worker got its task. */
  queue?: string;
  /** Time the worker started processing the task. */
  started?: string;
  /** ID of the task the worker is processing. */
  taskID?: string;
  /** Payload of the task the worker is processing. */
  taskPayload?: number[];
  /** Type of the task the worker is processing. */
  taskType?: string;
}
