/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { TimeDuration } from './timeDuration';

export interface AsynqQueueInfo {
  /** Number of active tasks. */
  active?: number;
  /** Number of aggregating tasks. */
  aggregating?: number;
  /** Number of archived tasks. */
  archived?: number;
  /** Number of stored completed tasks. */
  completed?: number;
  /** Total number of tasks failed to be processed within the given date (counter resets daily). */
  failed?: number;
  /** Total number of tasks failed (cumulative). */
  failedTotal?: number;
  /** Groups is the total number of groups in the queue. */
  groups?: number;
  /** Latency of the queue, measured by the oldest pending task in the queue. */
  latency?: TimeDuration;
  /** Total number of bytes that the queue and its tasks require to be stored in redis.
It is an approximate memory usage value in bytes since the value is computed by sampling. */
  memoryUsage?: number;
  /** Paused indicates whether the queue is paused.
If true, tasks in the queue will not be processed. */
  paused?: boolean;
  /** Number of pending tasks. */
  pending?: number;
  /** Total number of tasks being processed within the given date (counter resets daily).
The number includes both succeeded and failed tasks. */
  processed?: number;
  /** Total number of tasks processed (cumulative). */
  processedTotal?: number;
  /** Name of the queue. */
  queue?: string;
  /** Number of retry tasks. */
  retry?: number;
  /** Number of scheduled tasks. */
  scheduled?: number;
  /** Size is the total number of tasks in the queue.
The value is the sum of Pending, Active, Scheduled, Retry, Aggregating and Archived. */
  size?: number;
  /** Time when this queue info snapshot was taken. */
  timestamp?: string;
}
