/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { AsynqTask } from './asynqTask';

export interface AsynqSchedulerEntry {
  /** Identifier of this entry. */
  id?: string;
  /** Next shows the next time the task will be enqueued. */
  next?: string;
  /** Opts is the options for the periodic task. */
  opts?: unknown[];
  /** Prev shows the last time the task was enqueued.
Zero time if task was never enqueued. */
  prev?: string;
  /** Spec describes the schedule of this entry. */
  spec?: string;
  /** Periodic Task registered for this entry. */
  task?: AsynqTask;
}
