/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

export type AsynqTaskState = typeof AsynqTaskState[keyof typeof AsynqTaskState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AsynqTaskState = {
  TaskStateActive: 1,
  TaskStatePending: 2,
  TaskStateScheduled: 3,
  TaskStateRetry: 4,
  TaskStateArchived: 5,
  TaskStateCompleted: 6,
  TaskStateAggregating: 7,
} as const;
