/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform that provides scalable browser sessions and worker pool management.
 * OpenAPI spec version: 1.0
 */

export type GetApiV1WorkersParams = {
/**
 * Filter by work pool ID (UUID)
 */
pool_id?: string;
/**
 * Filter by online status
 */
online?: boolean;
};
