/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform that provides scalable browser sessions and worker pool management.
 * OpenAPI spec version: 1.0
 */

export type GetApiV1SessionsStatus = typeof GetApiV1SessionsStatus[keyof typeof GetApiV1SessionsStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV1SessionsStatus = {
  pending: 'pending',
  starting: 'starting',
  available: 'available',
  claimed: 'claimed',
  running: 'running',
  idle: 'idle',
  completed: 'completed',
  failed: 'failed',
  expired: 'expired',
  crashed: 'crashed',
  timed_out: 'timed_out',
  terminated: 'terminated',
} as const;
