/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { GetApiV1SessionsStatus } from './getApiV1SessionsStatus';

export type GetApiV1SessionsParams = {
/**
 * Filter by session status
 */
status?: GetApiV1SessionsStatus;
/**
 * Filter sessions created after this time (RFC3339 format)
 */
start_time?: string;
/**
 * Filter sessions created before this time (RFC3339 format)
 */
end_time?: string;
/**
 * Number of sessions to skip
 * @minimum 0
 */
offset?: number;
/**
 * Maximum number of sessions to return
 * @minimum 1
 * @maximum 1000
 */
limit?: number;
};
