/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

export type GetApiV1MonitoringMetricsRange = typeof GetApiV1MonitoringMetricsRange[keyof typeof GetApiV1MonitoringMetricsRange];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV1MonitoringMetricsRange = {
  '5m': '5m',
  '30m': '30m',
  '1h': '1h',
  '6h': '6h',
  '1d': '1d',
  '7d': '7d',
} as const;
