/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { GetApiV1ProfilesBrowser } from './getApiV1ProfilesBrowser';

export type GetApiV1ProfilesParams = {
/**
 * Filter by browser type
 */
browser?: GetApiV1ProfilesBrowser;
/**
 * Number of profiles to skip
 * @minimum 0
 */
offset?: number;
/**
 * Maximum number of profiles to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
