/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform that provides scalable browser sessions and worker pool management.
 * OpenAPI spec version: 1.0
 */
import type { GetApiV1SessionsStatus } from './getApiV1SessionsStatus';

export type GetApiV1SessionsParams = {
/**
 * Filter by session status
 */
status?: GetApiV1SessionsStatus;
/**
 * Filter sessions created after this time (RFC3339)
 */
start_time?: string;
/**
 * Filter sessions created before this time (RFC3339)
 */
end_time?: string;
/**
 * Pagination offset
 */
offset?: number;
/**
 * Pagination limit
 */
limit?: number;
};
