/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

export type GetApiV1DeploymentsIdRunsParams = {
/**
 * Filter by run status
 */
status?: string;
/**
 * Number of runs to skip
 */
offset?: number;
/**
 * Maximum number of runs to return
 */
limit?: number;
};
