/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { GetApiV1EventsEventType } from './getApiV1EventsEventType';

export type GetApiV1EventsParams = {
/**
 * Session ID (UUID) - alternative to path parameter
 */
session_id?: string;
/**
 * Filter by event type
 */
event_type?: GetApiV1EventsEventType;
/**
 * Filter events after this time (RFC3339 format)
 */
start_time?: string;
/**
 * Filter events before this time (RFC3339 format)
 */
end_time?: string;
/**
 * Number of events to skip
 * @minimum 0
 */
offset?: number;
/**
 * Maximum number of events to return
 * @minimum 1
 * @maximum 1000
 */
limit?: number;
};
