/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform that provides scalable browser sessions and worker pool management.
 * OpenAPI spec version: 1.0
 */
import type { GetApiV1SessionsIdEventsEventType } from './getApiV1SessionsIdEventsEventType';

export type GetApiV1SessionsIdEventsParams = {
/**
 * Filter by event type
 */
event_type?: GetApiV1SessionsIdEventsEventType;
/**
 * Filter events created after this time (RFC3339)
 */
start_time?: string;
/**
 * Filter events created before this time (RFC3339)
 */
end_time?: string;
/**
 * Pagination offset
 */
offset?: number;
/**
 * Pagination limit
 */
limit?: number;
};
