/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { GetApiV1MonitoringMetricsRange } from './getApiV1MonitoringMetricsRange';

export type GetApiV1MonitoringMetricsParams = {
/**
 * Time range
 */
range?: GetApiV1MonitoringMetricsRange;
/**
 * Queue names to filter
 */
queues?: string[];
};
