/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

export type GetApiV1DeploymentsParams = {
/**
 * Filter by deployment status
 */
status?: string;
/**
 * Filter by runtime
 */
runtime?: string;
/**
 * Number of deployments to skip
 */
offset?: number;
/**
 * Maximum number of deployments to return
 */
limit?: number;
};
