/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { InternalDeploymentsDeploymentRun } from './internalDeploymentsDeploymentRun';

export interface InternalDeploymentsDeploymentRunListResponse {
  limit?: number;
  offset?: number;
  runs?: InternalDeploymentsDeploymentRun[];
  total?: number;
}
