/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { InternalMonitoringMetricsDataPoint } from './internalMonitoringMetricsDataPoint';

export interface InternalMonitoringQueueMetrics {
  error_rate?: InternalMonitoringMetricsDataPoint[];
  queue?: string;
  queue_size?: InternalMonitoringMetricsDataPoint[];
  tasks_failed?: InternalMonitoringMetricsDataPoint[];
  tasks_processed?: InternalMonitoringMetricsDataPoint[];
}
