/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

export interface InternalProfilesUpdateProfileRequest {
  /** @maxLength 1000 */
  description?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
}
