/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { InternalDeploymentsBrowserRequest } from './internalDeploymentsBrowserRequest';
import type { InternalDeploymentsDeploymentConfigEnvironment } from './internalDeploymentsDeploymentConfigEnvironment';
import type { InternalDeploymentsDeploymentConfigResourceLimits } from './internalDeploymentsDeploymentConfigResourceLimits';

/**
 * Deployment configuration settings
 */
export interface InternalDeploymentsDeploymentConfig {
  browser_requests?: InternalDeploymentsBrowserRequest[];
  concurrency?: number;
  environment?: InternalDeploymentsDeploymentConfigEnvironment;
  max_retries?: number;
  resource_limits?: InternalDeploymentsDeploymentConfigResourceLimits;
  schedule?: string;
  timeout_seconds?: number;
  trigger_events?: string[];
}
