/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

export type InternalProfilesStorageBackend = typeof InternalProfilesStorageBackend[keyof typeof InternalProfilesStorageBackend];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InternalProfilesStorageBackend = {
  StorageBackendLocal: 'local',
  StorageBackendS3: 's3',
} as const;
