/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { InternalDeploymentsBrowserRequestEnvironment } from './internalDeploymentsBrowserRequestEnvironment';
import type { InternalDeploymentsBrowserRequestScreen } from './internalDeploymentsBrowserRequestScreen';

/**
 * Browser session configuration for deployment
 */
export interface InternalDeploymentsBrowserRequest {
  browser?: string;
  environment?: InternalDeploymentsBrowserRequestEnvironment;
  headless?: boolean;
  operating_system?: string;
  profile_id?: string;
  screen?: InternalDeploymentsBrowserRequestScreen;
  version?: string;
}
