/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { InternalMonitoringWorkerInfoSnakeCase } from './internalMonitoringWorkerInfoSnakeCase';
import type { InternalMonitoringServerInfoSnakeCaseQueues } from './internalMonitoringServerInfoSnakeCaseQueues';

/**
 * Asynq server info with snake_case fields
 */
export interface InternalMonitoringServerInfoSnakeCase {
  active_workers?: InternalMonitoringWorkerInfoSnakeCase[];
  concurrency?: number;
  host?: string;
  id?: string;
  pid?: number;
  queues?: InternalMonitoringServerInfoSnakeCaseQueues;
  started?: string;
  status?: string;
  strict_priority?: boolean;
}
