/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { InternalDeploymentsDeployment } from './internalDeploymentsDeployment';
import type { RunStatus } from './runStatus';

/**
 * Deployment run with execution details and results
 */
export interface InternalDeploymentsDeploymentRun {
  completed_at?: string;
  created_at?: string;
  /** Relationships */
  deployment?: InternalDeploymentsDeployment;
  deployment_id?: string;
  /** Computed fields */
  duration_seconds?: number;
  error?: string;
  id?: string;
  output?: number[];
  session_id?: string;
  started_at?: string;
  status?: RunStatus;
  updated_at?: string;
}
