/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

/**
 * Asynq worker info with snake_case fields
 */
export interface InternalMonitoringWorkerInfoSnakeCase {
  deadline?: string;
  queue?: string;
  started?: string;
  task_id?: string;
  task_payload?: number[];
  task_type?: string;
}
