/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { InternalMonitoringMetricsDataPoint } from './internalMonitoringMetricsDataPoint';
import type { InternalMonitoringSystemMetricsQueueMetrics } from './internalMonitoringSystemMetricsQueueMetrics';

export interface InternalMonitoringSystemMetrics {
  error_rate?: InternalMonitoringMetricsDataPoint[];
  queue_metrics?: InternalMonitoringSystemMetricsQueueMetrics;
  tasks_failed?: InternalMonitoringMetricsDataPoint[];
  tasks_processed?: InternalMonitoringMetricsDataPoint[];
}
