/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { MonitoringInfoQueueHealth } from './monitoringInfoQueueHealth';
import type { MonitoringInfoQueueStats } from './monitoringInfoQueueStats';
import type { ServerStats } from './serverStats';
import type { AsynqServerInfo } from './asynqServerInfo';

export interface MonitoringInfo {
  queue_health?: MonitoringInfoQueueHealth;
  queue_stats?: MonitoringInfoQueueStats;
  server_stats?: ServerStats;
  servers?: AsynqServerInfo[];
  timestamp?: string;
}
