/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

/**
 * Browser type
 */
export type PostApiV1ProfilesImportBodyBrowser = typeof PostApiV1ProfilesImportBodyBrowser[keyof typeof PostApiV1ProfilesImportBodyBrowser];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiV1ProfilesImportBodyBrowser = {
  chrome: 'chrome',
  chromium: 'chromium',
  firefox: 'firefox',
  edge: 'edge',
  webkit: 'webkit',
  safari: 'safari',
} as const;
