/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { PostApiV1ProfilesImportBodyBrowser } from './postApiV1ProfilesImportBodyBrowser';

export type PostApiV1ProfilesImportBody = {
  /** Profile ZIP archive */
  file: Blob;
  /** Profile name */
  name: string;
  /** Profile description */
  description?: string;
  /** Browser type */
  browser: PostApiV1ProfilesImportBodyBrowser;
};
