/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

/**
 * Proxy configuration with URL and optional credentials
 */
export interface ProxyConfig {
  proxy_password?: string;
  proxy_url?: string;
  proxy_username?: string;
}
