/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

export interface QueueHealth {
  active?: number;
  archived?: number;
  completed?: number;
  message?: string;
  paused?: boolean;
  pending?: number;
  retry?: number;
  scheduled?: number;
  /** "healthy", "warning", "critical", "error", "paused" */
  status?: string;
}
