/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

/**
 * Resource limits for CPU, memory and timeout
 */
export interface ResourceLimits {
  cpu?: number;
  memory?: string;
  timeout_minutes?: number;
}
