/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform that provides scalable browser sessions and worker pool management.
 * OpenAPI spec version: 1.0
 */

/**
 * Resource limits for CPU, memory and timeout
 */
export interface ResourceLimits {
  cpu?: number;
  memory?: string;
  timeout_minutes?: number;
}
