/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

/**
 * Current status of a deployment run
 */
export type RunStatus = typeof RunStatus[keyof typeof RunStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RunStatus = {
  RunStatusPending: 'pending',
  RunStatusRunning: 'running',
  RunStatusCompleted: 'completed',
  RunStatusFailed: 'failed',
  RunStatusCancelled: 'cancelled',
} as const;
