/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform that provides scalable browser sessions and worker pool management.
 * OpenAPI spec version: 1.0
 */

/**
 * Scaling parameters for updating work pool configuration
 */
export interface ScalingRequest {
  auto_scale?: boolean;
  /** @minimum 1 */
  max_concurrency?: number;
  /** @minimum 0 */
  max_idle_time?: number;
  /** @minimum 60 */
  max_session_duration?: number;
  /** @minimum 0 */
  min_size?: number;
  paused?: boolean;
}
