/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

/**
 * Screen configuration with width, height, DPI and scale
 */
export interface ScreenConfig {
  dpi?: number;
  height?: number;
  scale?: number;
  width?: number;
}
