/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform that provides scalable browser sessions and worker pool management.
 * OpenAPI spec version: 1.0
 */

/**
 * Screen configuration with width, height, DPI and scale
 */
export interface ScreenConfig {
  dpi?: number;
  height?: number;
  scale?: number;
  width?: number;
}
