/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { ServerStatsTotalQueues } from './serverStatsTotalQueues';

export interface ServerStats {
  active_servers?: number;
  /** queue name -> count of servers processing it */
  total_queues?: ServerStatsTotalQueues;
  total_servers?: number;
}
