/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

/**
 * Types of events that can occur during a session
 */
export type SessionEventType = typeof SessionEventType[keyof typeof SessionEventType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SessionEventType = {
  EvtSessionCreated: 'session_created',
  EvtResourceAllocated: 'resource_allocated',
  EvtSessionStarting: 'session_starting',
  EvtContainerStarted: 'container_started',
  EvtBrowserStarted: 'browser_started',
  EvtSessionAvailable: 'session_available',
  EvtSessionClaimed: 'session_claimed',
  EvtSessionAssigned: 'session_assigned',
  EvtSessionReady: 'session_ready',
  EvtSessionActive: 'session_active',
  EvtSessionIdle: 'session_idle',
  EvtHeartbeat: 'heartbeat',
  EvtPoolAdded: 'pool_added',
  EvtPoolRemoved: 'pool_removed',
  EvtPoolDrained: 'pool_drained',
  EvtSessionCompleted: 'session_completed',
  EvtSessionExpired: 'session_expired',
  EvtSessionTimedOut: 'session_timed_out',
  EvtSessionTerminated: 'session_terminated',
  EvtStartupFailed: 'startup_failed',
  EvtBrowserCrashed: 'browser_crashed',
  EvtContainerCrashed: 'container_crashed',
  EvtResourceExhausted: 'resource_exhausted',
  EvtNetworkError: 'network_error',
  EvtStatusChanged: 'status_changed',
  EvtConfigUpdated: 'config_updated',
  EvtHealthCheck: 'health_check',
} as const;
