/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { Browser } from './browser';
import type { SessionEnvironment } from './sessionEnvironment';
import type { OperatingSystem } from './operatingSystem';
import type { ProxyConfig } from './proxyConfig';
import type { ResourceLimits } from './resourceLimits';
import type { ScreenConfig } from './screenConfig';
import type { SessionStatus } from './sessionStatus';
import type { BrowserVersion } from './browserVersion';

/**
 * Browser session with configuration and status
 */
export interface Session {
  available_at?: string;
  browser?: Browser;
  claimed_at?: string;
  claimed_by?: string;
  container_id?: string;
  container_network?: string;
  created_at?: string;
  environment?: SessionEnvironment;
  expires_at?: string;
  headless?: boolean;
  id?: string;
  is_pooled?: boolean;
  live_url?: string;
  operating_system?: OperatingSystem;
  pool_id?: string;
  profile_id?: string;
  provider?: string;
  proxy?: ProxyConfig;
  resource_limits?: ResourceLimits;
  screen?: ScreenConfig;
  status?: SessionStatus;
  updated_at?: string;
  version?: BrowserVersion;
  webhooks_enabled?: boolean;
  work_pool_id?: string;
  ws_endpoint?: string;
}
