/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { SessionEvent } from './sessionEvent';

/**
 * Response containing a list of session events with pagination info
 */
export interface SessionEventListResponse {
  events?: SessionEvent[];
  limit?: number;
  offset?: number;
  total?: number;
}
