/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform that provides scalable browser sessions and worker pool management.
 * OpenAPI spec version: 1.0
 */

/**
 * Performance metrics including CPU, memory and network usage
 */
export interface SessionMetrics {
  cpu_percent?: number;
  id?: string;
  memory_mb?: number;
  network_rx_bytes?: number;
  network_tx_bytes?: number;
  session_id?: string;
  timestamp?: string;
}
