/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

/**
 * Current status of a browser session
 */
export type SessionStatus = typeof SessionStatus[keyof typeof SessionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SessionStatus = {
  StatusPending: 'pending',
  StatusStarting: 'starting',
  StatusAvailable: 'available',
  StatusClaimed: 'claimed',
  StatusRunning: 'running',
  StatusIdle: 'idle',
  StatusCompleted: 'completed',
  StatusFailed: 'failed',
  StatusExpired: 'expired',
  StatusCrashed: 'crashed',
  StatusTimedOut: 'timed_out',
  StatusTerminated: 'terminated',
} as const;
