/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform that provides scalable browser sessions and worker pool management.
 * OpenAPI spec version: 1.0
 */
import type { SessionEvent } from './sessionEvent';

/**
 * Response containing a list of session events with pagination info
 */
export interface SessionEventListResponse {
  events?: SessionEvent[];
  limit?: number;
  offset?: number;
  total?: number;
}
