/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */
import type { AsynqTaskInfo } from './asynqTaskInfo';

export interface TaskInfo {
  active_tasks?: AsynqTaskInfo[];
  archived_tasks?: AsynqTaskInfo[];
  pending_tasks?: AsynqTaskInfo[];
  queue?: string;
  retry_tasks?: AsynqTaskInfo[];
  scheduled_tasks?: AsynqTaskInfo[];
}
