/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform using task queues for scalable browser session management.
 * OpenAPI spec version: 2.0
 */

export type TimeDuration = typeof TimeDuration[keyof typeof TimeDuration];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimeDuration = {
  minDuration: -9223372036854776000,
  maxDuration: 9223372036854776000,
  Nanosecond: 1,
  Microsecond: 1000,
  Millisecond: 1000000,
  Second: 1000000000,
  Minute: 60000000000,
  Hour: 3600000000000,
} as const;
