/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform that provides scalable browser sessions and worker pool management.
 * OpenAPI spec version: 1.0
 */

/**
 * Heartbeat data with active session count
 */
export interface WorkerHeartbeatRequest {
  /** @minimum 0 */
  active?: number;
}
