/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * BrowserGrid API
 * BrowserGrid is a distributed browser automation platform that provides scalable browser sessions and worker pool management.
 * OpenAPI spec version: 1.0
 */
import type { ProviderType } from './providerType';

/**
 * Worker instance that handles browser sessions
 */
export interface Worker {
  active?: number;
  hostname?: string;
  id?: string;
  last_beat?: string;
  max_slots?: number;
  name?: string;
  paused?: boolean;
  pool_id?: string;
  provider?: ProviderType;
  started_at?: string;
}
